sudo: required
services:
  - docker

before_install:
  - docker build -t sh4rif/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true sh4rif/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-456255276660"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
